services:
  
  python-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: insight-agent
    restart: always
    env_file:
    - ../.env
    environment:
      - PYTHONUNBUFFERED=1
      # Use internal services by default; override via .env if you want cloud
      - MONGO_URI=mongodb://admin:admin@mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
      - REDIS_USERNAME=
      - REDIS_SSL=false
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - storage:/data
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", 'exec 3<>/dev/tcp/localhost/8000; echo -e "GET / HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3; cat <&3']
      interval: 5s
      timeout: 1s
      retries: 3

  frontend:
    image: node:18-alpine
    container_name: insight-frontend
    working_dir: /app
    environment:
      # Ensure the frontend talks to the backend exposed by python-app
      - NEXT_PUBLIC_BASE_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ../src/frontend:/app
      - /app/node_modules
    command: sh -lc "npm ci || npm install && npx next dev -H 0.0.0.0 -p 3000"
    depends_on:
      - python-app

  frontend-prod:
    profiles: ["prod"]
    build:
      context: ../src/frontend
      dockerfile: Dockerfile
    container_name: insight-frontend-prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - python-app

  mongodb:
    image: mongo:8.0-noble
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Set the MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: admin # Set the MongoDB root password
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data
    # healthcheck:
    #   test: ["CMD-SHELL", "mongosh", "mongodb://admin:admin@localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 })" ]
    #   interval: 5s
    #   timeout: 1s
    #   retries: 3
    # MONGO_URI="mongodb://admin:admin@mongodb:27017"

  redis:
    image: redis:7.0.0-alpine
    restart: always
    environment:
      TZ: UTC # Sets the timezone
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "no", "--save", "60", "1", "--loglevel", "warning", "--requirepass", "admin"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "-a", "admin", "ping"]
      interval: 5s
      timeout: 1s
      retries: 3
    # REDIS_BROKER_URL="redis://:admin@redis:6379"

volumes:
  mongodb_data: # Define the mongodb data volume
  redis_data: # Define the redis data volume
  qdrant_data: # Define the qdrant data volume
  storage: # Define the storage volume
